http:
  routers:
    crawlervision-crawlervision-lh-http:
      rule: Host(`crawlervision.lh`)
      service: crawlervision-crawlervision-lh-svc
      entryPoints:
      - web
    crawlervision-crawlervision-lh-https:
      rule: Host(`crawlervision.lh`)
      service: crawlervision-crawlervision-lh-svc
      entryPoints:
      - websecure
      tls: true
    crawlervision-api-crawlervision-lh-http:
      rule: Host(`api.crawlervision.lh`)
      service: crawlervision-api-crawlervision-lh-svc
      entryPoints:
      - web
    crawlervision-api-crawlervision-lh-https:
      rule: Host(`api.crawlervision.lh`)
      service: crawlervision-api-crawlervision-lh-svc
      entryPoints:
      - websecure
      tls: true
    crawlervision-cf-kv-http:
      rule: Host(`crawlervision-kv.lh`)
      service: kv-service
      entryPoints:
      - web
    crawlervision-cf-kv-https:
      rule: Host(`crawlervision-kv.lh`)
      service: kv-service
      entryPoints:
      - websecure
      tls: true
    crawlervision-cf-r2-http:
      rule: Host(`crawlervision-r2.lh`)
      service: r2-service
      entryPoints:
      - web
    crawlervision-cf-r2-https:
      rule: Host(`crawlervision-r2.lh`)
      service: r2-service
      entryPoints:
      - websecure
      tls: true
    crawlervision-cf-d1-http:
      rule: Host(`crawlervision-d1.lh`)
      service: d1-service
      entryPoints:
      - web
    crawlervision-cf-d1-https:
      rule: Host(`crawlervision-d1.lh`)
      service: d1-service
      entryPoints:
      - websecure
      tls: true
    1note-1note-lh-http:
      rule: Host(`1note.lh`)
      service: 1note-1note-lh-svc
      entryPoints:
      - web
    1note-1note-lh-https:
      rule: Host(`1note.lh`)
      service: 1note-1note-lh-svc
      entryPoints:
      - websecure
      tls: true
    1note-api-1note-lh-http:
      rule: Host(`api.1note.lh`)
      service: 1note-api-1note-lh-svc
      entryPoints:
      - web
    1note-api-1note-lh-https:
      rule: Host(`api.1note.lh`)
      service: 1note-api-1note-lh-svc
      entryPoints:
      - websecure
      tls: true
    1note-cf-kv-http:
      rule: Host(`1note-kv.lh`)
      service: kv-service
      entryPoints:
      - web
    1note-cf-kv-https:
      rule: Host(`1note-kv.lh`)
      service: kv-service
      entryPoints:
      - websecure
      tls: true
    1note-cf-r2-http:
      rule: Host(`1note-r2.lh`)
      service: r2-service
      entryPoints:
      - web
    1note-cf-r2-https:
      rule: Host(`1note-r2.lh`)
      service: r2-service
      entryPoints:
      - websecure
      tls: true
    1note-cf-d1-http:
      rule: Host(`1note-d1.lh`)
      service: d1-service
      entryPoints:
      - web
    1note-cf-d1-https:
      rule: Host(`1note-d1.lh`)
      service: d1-service
      entryPoints:
      - websecure
      tls: true
    kanakraj-kanakraj-lh-http:
      rule: Host(`kanakraj.lh`)
      service: kanakraj-kanakraj-lh-svc
      entryPoints:
      - web
    kanakraj-kanakraj-lh-https:
      rule: Host(`kanakraj.lh`)
      service: kanakraj-kanakraj-lh-svc
      entryPoints:
      - websecure
      tls: true
    kanakraj-api-kanakraj-lh-http:
      rule: Host(`api.kanakraj.lh`)
      service: kanakraj-api-kanakraj-lh-svc
      entryPoints:
      - web
    kanakraj-api-kanakraj-lh-https:
      rule: Host(`api.kanakraj.lh`)
      service: kanakraj-api-kanakraj-lh-svc
      entryPoints:
      - websecure
      tls: true
    kanakraj-cf-kv-http:
      rule: Host(`kanakraj-kv.lh`)
      service: kv-service
      entryPoints:
      - web
    kanakraj-cf-kv-https:
      rule: Host(`kanakraj-kv.lh`)
      service: kv-service
      entryPoints:
      - websecure
      tls: true
    kanakraj-cf-r2-http:
      rule: Host(`kanakraj-r2.lh`)
      service: r2-service
      entryPoints:
      - web
    kanakraj-cf-r2-https:
      rule: Host(`kanakraj-r2.lh`)
      service: r2-service
      entryPoints:
      - websecure
      tls: true
    kanakraj-cf-d1-http:
      rule: Host(`kanakraj-d1.lh`)
      service: d1-service
      entryPoints:
      - web
    kanakraj-cf-d1-https:
      rule: Host(`kanakraj-d1.lh`)
      service: d1-service
      entryPoints:
      - websecure
      tls: true
  services:
    crawlervision-crawlervision-lh-svc:
      loadBalancer:
        servers:
        - url: http://cv-frontend:3000
    crawlervision-api-crawlervision-lh-svc:
      loadBalancer:
        servers:
        - url: http://cv-backend:8001
    1note-1note-lh-svc:
      loadBalancer:
        servers:
        - url: http://1note-frontend-1:3000
    1note-api-1note-lh-svc:
      loadBalancer:
        servers:
        - url: http://1note-backend-1:8001
    kanakraj-kanakraj-lh-svc:
      loadBalancer:
        servers:
        - url: http://kanakraj-frontend-1:80
    kanakraj-api-kanakraj-lh-svc:
      loadBalancer:
        servers:
        - url: http://kanakraj-frontend-1:80
